#
# Run repoman via travis
# See https://github.com/ShyPixie/repoman-travis
#
language: python
python:
    - pypy
env:
    - PORTAGE_VER="2.2.20.1"
before_script:
    - mkdir travis-overlay
    - mv !(travis-overlay) travis-overlay/
    - mv .git travis-overlay/
    - wget "https://raw.githubusercontent.com/ShyPixie/repoman-travis/master/.travis.yml" -O .travis.yml.upstream
    - wget "https://github.com/gentoo/portage/archive/v${PORTAGE_VER}.tar.gz" -O portage-${PORTAGE_VER}.tar.gz
    - wget "https://raw.githubusercontent.com/ShyPixie/repoman-travis/master/spinner.sh"
    - wget "https://github.com/gentoo/gentoo-portage-rsync-mirror/archive/master.tar.gz" -O portage-tree.tar.gz
    - sudo chmod a+rwX /etc/passwd /etc/group /etc /usr spinner.sh
    - chmod a+rwx spinner.sh
    - echo "portage:x:250:250:portage:/var/tmp/portage:/bin/false" >> /etc/passwd
    - echo "portage::250:portage,travis" >> /etc/group
    - mkdir -p /etc/portage/ /usr/portage/distfiles
    - tar xzf portage-${PORTAGE_VER}.tar.gz
    - tar xzf portage-tree.tar.gz -C /usr/portage --strip-components=1
    - cp portage-${PORTAGE_VER}/cnf/repos.conf /etc/portage/
    - ln -s /usr/portage/profiles/base/ /etc/portage/make.profile
    - wget "https://www.gentoo.org/dtd/metadata.dtd" -O /usr/portage/distfiles/metadata.dtd
    - cd travis-overlay
script:
    - ./../spinner.sh "python ../portage-${PORTAGE_VER}/bin/repoman -Sd --without-mask full"
